graph TB
["/"]
.-->
.git[".git/"]
.-->.git
.git_branches[".git/branches/"]
.git-->.git_branches
.git_hooks[".git/hooks/"]
.git-->.git_hooks
.git_info[".git/info/"]
.git-->.git_info
.git_logs[".git/logs/"]
.git-->.git_logs
.git_logs_refs[".git/logs/refs/"]
.git_logs-->.git_logs_refs
.git_logs_refs_heads[".git/logs/refs/heads/"]
.git_logs_refs-->.git_logs_refs_heads
.git_logs_refs_remotes[".git/logs/refs/remotes/"]
.git_logs_refs-->.git_logs_refs_remotes
.git_logs_refs_remotes_origin[".git/logs/refs/remotes/origin/"]
.git_logs_refs_remotes-->.git_logs_refs_remotes_origin
.git_objects[".git/objects/"]
.git-->.git_objects
.git_objects_1c[".git/objects/1c/"]
.git_objects-->.git_objects_1c
.git_objects_1f[".git/objects/1f/"]
.git_objects-->.git_objects_1f
.git_objects_27[".git/objects/27/"]
.git_objects-->.git_objects_27
.git_objects_62[".git/objects/62/"]
.git_objects-->.git_objects_62
.git_objects_a5[".git/objects/a5/"]
.git_objects-->.git_objects_a5
.git_objects_fe[".git/objects/fe/"]
.git_objects-->.git_objects_fe
.git_objects_info[".git/objects/info/"]
.git_objects-->.git_objects_info
.git_objects_pack[".git/objects/pack/"]
.git_objects-->.git_objects_pack
.git_refs[".git/refs/"]
.git-->.git_refs
.git_refs_heads[".git/refs/heads/"]
.git_refs-->.git_refs_heads
.git_refs_remotes[".git/refs/remotes/"]
.git_refs-->.git_refs_remotes
.git_refs_remotes_origin[".git/refs/remotes/origin/"]
.git_refs_remotes-->.git_refs_remotes_origin
.git_refs_tags[".git/refs/tags/"]
.git_refs-->.git_refs_tags
